Fixed minor spelling and grammatical errors, in addition to rephrasin…
virtual-labs/exp-tree-traversal-iiith pull request #11
Opened 2022-06-13 19:12 UTC by MaxGreenspan

Fixed minor spelling and grammatical errors.
Rephrased the Breadth First Traversal Practice section directions.

2022-06-16 17:15 UTC, raj-vlabs requested changes
Changes are generally fine, please take a look at a couple of comments

2022-06-16 17:15 UTC, raj-vlabs commented on experiment/breadth-first-traversal/simulation/bft-exercise.html
>  the traversal at the particular height is from right to left instead of left to right and this new BFT traversal is called Sudo BFT.
I think they mean pseudo BFT and not Sudo BFT

2022-06-16 17:15 UTC, raj-vlabs commented on experiment/breadth-first-traversal/simulation/bft-exercise.html
> +      <li>Perform a Sudo BFT (see question below).</li>
Pseudo BFT in place of Sudo BFT?

2022-06-16 19:13 UTC, MaxGreenspan commented on experiment/breadth-first-traversal/simulation/bft-exercise.html
> +      <li>Perform a Sudo BFT (see question below).</li>
Yes, I think you're right.

2022-06-17 04:24 UTC, raj-vlabs requested changes

2022-06-17 04:24 UTC, raj-vlabs commented on experiment/breadth-first-traversal/simulation/bft-exercise.html
> +        a Pseuudo BFT traversal.</li>
Please fix the typo in the spelling of pseudo

2022-09-12 06:23 UTC, merged